# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fab3171874754a93e0892c0031dfb888e3350d83b743601a7ff082be589e0d4a45a093a3c955b4acd34815e332407bae62ab74ec7a4654809c095117bed6f2c

test:
  secret_key_base: 2cc4b15be83088648874b5cebccda3841293bd38a93bd5d74cdcef82aad7141a84ff451d5b0fa87993420956cb003ef8612fc0b2a37576220b9437c7fdabc57d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
